### PR TITLE
docs: updated line 37 of Readme.md

### PR DESCRIPTION
**Pull request by amith1108**
docs: Updated the aws cli command in line 37 to  "aws iam create-policy --policy-name <YOUR_FSS_LAMBDA_POLICY> --policy-document file://fss-trust-policy.json"

### CODE REVIEW

**Comment by Laurence-Cheng** [comment]
Thank you, @amith1108 .
Would you please update the commit message because we are following this convention?
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by amith1108** [comment]
> Thank you, @amith1108 .
> Would you please update the commit message because we are following this convention?
> https://www.conventionalcommits.org/en/v1.0.0/

Hey Laurence, 

I updated the commit message. I'm not a pro in GitHub let me know if it's the right convention.

**Comment by carpusherw** [comment]
Hi @amith1108 ,
You just updated the PR title instead of the commit message. But no worry, I will do that for you with squash merge.

**Review by carpusherw — APPROVED** [review]
Merge Approval

**Comment by amith1108** [comment]
> Hi @amith1108 ,
> You just updated the PR title instead of the commit message. But no worry, I will do that for you with squash merge.

Oops my bad :(  
I thought I had to change both the message and the PR title. I'm trying to get a hang of this. :) 
Commit message is the first message in this conversation right? Did I get the convention right this time?

**Comment by carpusherw** [comment]
Here is your commit and its message.
https://github.com/trendmicro/cloudone-filestorage-plugins/pull/18/commits
The convention is good but I would suggest a better message like  `docs: Fix AWS CLI command to create a custom policy`.
To change the commit message, you could reference `git commit --amend` and `git push --f`. But I suppose you are only using Github GUI and don't have git installed. In that case, I will do it for you.

**Comment by carpusherw** [comment]
Merging with squash...

**Pull request merged**
