### PR TITLE
docs: adding a missing "protocol" flag to the SNS subscription creation CLI command.

### PR DESCRIPTION
**Pull request by andresark**
docs: adding a missing flag to the SNS subscription creation AWS CLI command.

### CODE REVIEW

**Comment by Laurence-Cheng** [comment]
Thank you, @andresark .
Would you please update the commit message because we are following this convention?
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by andresark** [comment]
Let me know if that suffices 👍

**Comment by carpusherw** [comment]
> Let me know if that suffices 👍

I don't think anything has changed. Did you push the change?

**Comment by Laurence-Cheng** [comment]
> > Let me know if that suffices 👍
> 
> I don't think anything has changed. Did you push the change?

Hi @andresark 

It looks like you only edited your first comment in this PR.
However, we are talking about the commit messages.
You can use `git commit --amend` to edit your latest commit messages.
Then you have to `force push` to update it to this PR.

**Comment by carpusherw** [comment]
#25

**Pull request closed without merging**
