### PR TITLE
fixed syntax error on line number 147 and 148

### PR DESCRIPTION
**Pull request by rohit-paygude**
# Syntax error

### CODE REVIEW

**Review by carpusherw — COMMENTED** [review]
Code LGTM.
Would you please update the commit message to follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) specification? See our [contributing guide](https://github.com/trendmicro/cloudone-filestorage-plugins/blob/master/.github/CONTRIBUTING.md) for more details.

**Comment by carpusherw** [comment]
Closes #59

**Review by Laurence-Cheng — COMMENTED** [review]
Code LGTM.

**Comment by carpusherw** [comment]
LGTM. Please squash the commits. See our [contributing guide](https://github.com/trendmicro/cloudone-filestorage-plugins/blob/master/.github/CONTRIBUTING.md) for more details.

**Comment by chenjill** [comment]
Hi @rohit-paygude, thank you for helping correcting the code. Could you help to squash the commits so that we could merge your contribution?

**Review by carpusherw — APPROVED** [review]
Review Approved

**Pull request merged**
